runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - run: pnpm i --frozen-lockfile
      shell: bash
